//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mighDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextReplace
    {
        public string OldText { get; set; }
        public string NewText { get; set; }
    }
}
