//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mighDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int idTrack { get; set; }
        public int idAlbum { get; set; }
        public string Title { get; set; }
        public byte TrackNumber { get; set; }
        public string FileName { get; set; }
        public string FileUrlName { get; set; }
    }
}
